# Funding options for OpenClaw Distributed Compute
# Documentation: https://docs.github.com/articles/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors
# github: [openclaw]

# Open Collective
# open_collective: openclaw-distributed-compute

# Patreon
# patreon: openclaw

# Ko-fi
# ko_fi: openclaw

# Custom sponsorship links
# custom: ["https://openclaw.org/sponsor", "https://openclaw.org/donate"]

# Note: Funding options will be configured once the project establishes
# official sponsorship channels. For now, the best way to support the
# project is through code contributions, testing, and community engagement.